#!/bin/bash

APT_SOFTWARE="zsh build-essential cmake python3-dev tmux exuberant-ctags ranger zathura python-dev python-pip python3-pip python3-setuptools"
PIP_SOFTWARE="mycli mu-repo terminal_velocity"
PIP3_SOFTWARE="thefuck"
RUST_SOFTWARE="rls-preview rust-analysis rust-src rustfmt-preview"


sudo apt install ${APT_SOFTWARE}

sudo pip install ${PIP_SOFTWARE}
sudo pip3 install ${PIP3_SOFTWARE}

# Install rust
if ! command -v pip > /dev/null; then
    curl https://sh.rustup.rs -sSf | sh
    rustup update
    rustup component add ${RUST_SOFTWARE}
fi


